const fs = require('fs');
const { WORD_PAIRS } = require('./server/src/wordPairs.js');

const customMapping = {
  // Animals
  dolphin: { e: '🐬', h: 'Leaps out of the ocean' },
  whale: { e: '🐋', h: 'The largest swimmer' },
  wolf: { e: '🐺', h: 'Howls at the moon' },
  fox: { e: '🦊', h: 'Sneaky and orange' },
  eagle: { e: '🦅', h: 'Soars high in the sky' },
  hawk: { e: '🦅', h: 'A sharp-eyed hunter' },
  frog: { e: '🐸', h: 'Hops near the pond' },
  toad: { e: '🐸', h: 'Bumpy and croaks' },
  alligator: { e: '🐊', h: 'Snaps in the swamp' },
  crocodile: { e: '🐊', h: 'Lurks in the river' },
  turtle: { e: '🐢', h: 'Carries its house' },
  tortoise: { e: '🐢', h: 'Slow and steady on land' },
  rabbit: { e: '🐰', h: 'Loves eating carrots' },
  hare: { e: '🐇', h: 'Fast and furry' },
  leopard: { e: '🐆', h: 'Spotted and fast' },
  cheetah: { e: '🐆', h: 'The fastest runner' },
  bison: { e: 's', h: 'Roams the plains' },
  buffalo: { e: '🐃', h: 'A heavy grazer' },
  donkey: { e: '🐴', h: 'Known to be stubborn' },
  mule: { e: '🐴', h: 'A hard worker' },
  crow: { e: '🐦‍⬛', h: 'Black and smart' },
  raven: { e: '🐦‍⬛', h: 'A dark, mystical bird' },
  sparrow: { e: '🐦', h: 'A common little bird' },
  finch: { e: '🐦', h: 'A colorful little flyer' },
  seal: { e: '🦭', h: 'Barks and claps' },
  "sea lion": { e: '🦭', h: 'Balances balls on its nose' },
  shrimp: { e: '🦐', h: 'Tiny and pink' },
  prawn: { e: '🦐', h: 'Delicious in a cocktail' },
  moth: { e: '🦋', h: 'Drawn to the flame' },
  butterfly: { e: '🦋', h: 'Starts as a caterpillar' },
  llama: { e: '🦙', h: 'Might spit at you' },
  alpaca: { e: '🦙', h: 'Very soft wool' },
  caterpillar: { e: '🐛', h: 'Crawls on leaves' },
  larva: { e: '🐛', h: 'Before it gets wings' },
  pigeon: { e: '🕊️', h: 'Hangs out in the city' },
  dove: { e: '🕊️', h: 'Symbol of peace' },
  panther: { e: '🐈‍⬛', h: 'Sleek and black' },
  jaguar: { e: '🐆', h: 'Spotted jungle cat' },
  otter: { e: '🦦', h: 'Holds hands while sleeping' },
  beaver: { e: '🦫', h: 'Builds dams in the river' },

  // Food
  pancake: { e: '🥞', h: 'Covered in syrup' },
  waffle: { e: '🧇', h: 'Has square pockets' },
  butter: { e: '🧈', h: 'Melts on toast' },
  margarine: { e: '🧈', h: 'A yellow spread' },
  sushi: { e: '🍣', h: 'Wrapped in seaweed' },
  sashimi: { e: '🍣', h: 'Fresh slices of fish' },
  cupcake: { e: '🧁', h: 'Has frosting on top' },
  muffin: { e: '🧁', h: 'A morning baked good' },
  coffee: { e: '☕', h: 'Your morning energy' },
  espresso: { e: '☕', h: 'A strong, tiny shot' },
  jam: { e: '🍓', h: 'Spread it on bread' },
  jelly: { e: '🍇', h: 'Sweet and wobbly' },
  soup: { e: '🥣', h: 'Eat it with a spoon' },
  stew: { e: '🍲', h: 'Thick and hearty' },
  pizza: { e: '🍕', h: 'Comes in a square box' },
  flatbread: { e: '🥖', h: 'Crispy and baked' },
  mango: { e: '🥭', h: 'Sweet and tropical' },
  papaya: { e: '🥭', h: 'Has lots of black seeds' },
  donut: { e: '🍩', h: 'Has a hole in the middle' },
  bagel: { e: '🥯', h: 'Great with cream cheese' },
  biscuit: { e: '🍪', h: 'Dip it in tea' },
  cracker: { e: '🍘', h: 'Crispy and salty' },
  milkshake: { e: '🥤', h: 'Drink it through a straw' },
  smoothie: { e: '🥤', h: 'Blended and fruity' },
  noodle: { e: '🍜', h: 'Slurp it from a bowl' },
  pasta: { e: '🍝', h: 'Covered in sauce' },
  taco: { e: '🌮', h: 'Folded and crunchy' },
  burrito: { e: '🌯', h: 'Wrapped in foil' },
  cake: { e: '🎂', h: 'Blow out the candles' },
  pie: { e: '🥧', h: 'Baked with a crust' },
  popcorn: { e: '🍿', h: 'Eat it at the movies' },
  "puffed rice": { e: '🍚', h: 'Light and airy' },
  lemonade: { e: '🍋', h: 'Sweet, sour, and cold' },
  limeade: { e: '🍋', h: 'Green and refreshing' },
  cereal: { e: '🥣', h: 'Pour milk on it' },
  granola: { e: '🥣', h: 'Crunchy morning snack' },
  lasagna: { e: '🍝', h: 'Layers of cheese and pasta' },
  moussaka: { e: '🍆', h: 'A baked dish' },
  pretzel: { e: '🥨', h: 'Twisted and salty' },
  breadstick: { e: '🥖', h: 'Served before the meal' },

  // Places
  beach: { e: '🏖️', h: 'Sand, sun, and waves' },
  desert: { e: '🏜️', h: 'Hot, dry, and sandy' },
  library: { e: '📚', h: 'Be quiet in here' },
  bookstore: { e: '📖', h: 'Where you buy stories' },
  hotel: { e: '🏨', h: 'Stay here on vacation' },
  motel: { e: '🏩', h: 'Stop here on a roadtrip' },
  castle: { e: '🏰', h: 'Where a king lives' },
  palace: { e: '🕌', h: 'A grand residence' },
  lake: { e: '🏞️', h: 'A calm body of water' },
  pond: { e: '🦆', h: 'Where the ducks swim' },
  museum: { e: '🏛️', h: 'Full of history' },
  gallery: { e: '🖼️', h: 'Look at the art' },
  cinema: { e: '🎬', h: 'Watch the big screen' },
  theatre: { e: '🎭', h: 'Watch a live play' },
  temple: { e: '⛩️', h: 'A place of worship' },
  shrine: { e: '⛩️', h: 'A sacred place' },
  clinic: { e: '⚕️', h: 'Go here when sick' },
  hospital: { e: '🏥', h: 'Where you get treated' },
  supermarket: { e: '🛒', h: 'Buy your groceries here' },
  grocery: { e: '🛒', h: 'Where you buy food' },
  gym: { e: '🏋️', h: 'Where you go to sweat' },
  studio: { e: '🩰', h: 'A room for practice' },
  lighthouse: { e: '🗼', h: 'Guides ships at night' },
  watchtower: { e: '🗼', h: 'Look out from here' },
  meadow: { e: '🌼', h: 'A field of grass' },
  prairie: { e: '🌾', h: 'Wide open grassy land' },
  swamp: { e: '🐊', h: 'Muddy and wet' },
  marsh: { e: '🐸', h: 'A wet wetland' },
  volcano: { e: '🌋', h: 'Erupts with lava' },
  geyser: { e: '⛲', h: 'Shoots hot water' },

  // Objects
  guitar: { e: '🎸', h: 'Strum the strings' },
  ukulele: { e: '🎸', h: 'Small and Hawaiian' },
  couch: { e: '🛋️', h: 'Sit and watch TV' },
  sofa: { e: '🛋️', h: 'Lounge on this' },
  sword: { e: '⚔️', h: 'Sharp and medieval' },
  dagger: { e: '🗡️', h: 'Short and sharp' },
  clock: { e: '🕰️', h: 'Tells you the time' },
  watch: { e: '⌚', h: 'Wear it on your wrist' },
  pillow: { e: '🛌', h: 'Rest your head here' },
  cushion: { e: '🛋️', h: 'Soft and comfortable' },
  lamp: { e: '💡', h: 'Turn it on to see' },
  lantern: { e: '🏮', h: 'Carry it in the dark' },
  mirror: { e: '🪞', h: 'Look at yourself' },
  window: { e: '🪟', h: 'Look outside' },
  rifle: { e: '🔫', h: 'A long firearm' },
  shotgun: { e: '🔫', h: 'A powerful firearm' },
  pen: { e: '🖊️', h: 'Write with ink' },
  pencil: { e: '✏️', h: 'Has an eraser on top' },
  mug: { e: '☕', h: 'Hold it by the handle' },
  cup: { e: '🍵', h: 'Drink out of it' },
  bucket: { e: '🪣', h: 'Fill it with water' },
  pail: { e: '🪣', h: 'Carry sand in it' },
  ladder: { e: '🪜', h: 'Climb up high' },
  staircase: { e: '🪜', h: 'Walk up to the next floor' },
  telescope: { e: '🔭', h: 'Look at the stars' },
  binoculars: { e: '🔭', h: 'Look at things far away' },
  violin: { e: '🎻', h: 'Play it with a bow' },
  cello: { e: '🎻', h: 'A large string instrument' },
  trumpet: { e: '🎺', h: 'Blow into the brass' },
  trombone: { e: '🎺', h: 'Slide the brass' },
  microscope: { e: '🔬', h: 'Look at tiny things' },
  magnifier: { e: '🔍', h: 'Make things look bigger' },
  thermos: { e: '🍶', h: 'Keeps your drink hot' },
  flask: { e: '🧪', h: 'Carry a sip with you' },
  compass: { e: '🧭', h: 'Always points North' },
  protractor: { e: '📐', h: 'Measures angles' },
  hammock: { e: '🛏️', h: 'Swing between trees' },
  swing: { e: '🛝', h: 'Push me higher' },
  gloves: { e: '🧤', h: 'Keep your hands warm' },
  mittens: { e: '🧤', h: 'No fingers, just a thumb' },

  // Activities
  swimming: { e: '🏊', h: 'Do this in a pool' },
  diving: { e: '🤿', h: 'Jump in head first' },
  painting: { e: '🎨', h: 'Create art on a canvas' },
  drawing: { e: '✏️', h: 'Sketch on paper' },
  jogging: { e: '🏃', h: 'A steady run' },
  sprinting: { e: '🏃', h: 'Run as fast as you can' },
  camping: { e: '⛺', h: 'Sleep in a tent' },
  hiking: { e: '🥾', h: 'Walk up a mountain' },
  singing: { e: '🎤', h: 'Use your voice' },
  humming: { e: '🎵', h: 'Make a sound with your mouth closed' },
  knitting: { e: '🧶', h: 'Make a sweater with yarn' },
  crocheting: { e: '🧶', h: 'Hooking yarn together' },
  surfing: { e: '🏄', h: 'Ride the waves' },
  wakeboarding: { e: '🏄', h: 'Pulled by a boat' },
  boxing: { e: '🥊', h: 'Punch with big gloves' },
  wrestling: { e: '🤼', h: 'Grapple on a mat' },
  skiing: { e: '🎿', h: 'Slide down the snow' },
  snowboarding: { e: '🏂', h: 'Ride the snow sideways' },
  gardening: { e: '🪴', h: 'Plant flowers and vegetables' },
  farming: { e: '🚜', h: 'Grow crops on a large scale' },
  baking: { e: '🧁', h: 'Make a cake in the oven' },
  cooking: { e: '🍳', h: 'Make a meal on the stove' },
  cycling: { e: '🚴', h: 'Pedal down the street' },
  skating: { e: '⛸️', h: 'Glide on ice or wheels' },
  fishing: { e: '🎣', h: 'Catch something in the water' },
  hunting: { e: '🏹', h: 'Track and capture' },
  meditation: { e: '🧘', h: 'Sit quietly and breathe' },
  yoga: { e: '🧘', h: 'Stretch and pose' },
  photography: { e: '📷', h: 'Take a picture' },
  videography: { e: '📹', h: 'Record a movie' },

  // Clothing
  jacket: { e: '🧥', h: 'Zip it up when it is cold' },
  coat: { e: '🧥', h: 'Wear it in the winter' },
  sandals: { e: '🩴', h: 'Wear them to the beach' },
  slippers: { e: '🥿', h: 'Wear them around the house' },
  cap: { e: '🧢', h: 'Wear it on your head' },
  hat: { e: '🎩', h: 'Keeps the sun out of your eyes' },
  scarf: { e: '🧣', h: 'Wrap it around your neck' },
  shawl: { e: '🧣', h: 'Drape it over your shoulders' },
  shirt: { e: '👕', h: 'Has sleeves and a collar' },
  blouse: { e: '👚', h: 'A nice top to wear' },
  trousers: { e: '👖', h: 'Wear them on your legs' },
  leggings: { e: '👖', h: 'Tight and stretchy' },
  sneakers: { e: '👟', h: 'Lace them up to run' },
  trainers: { e: '👟', h: 'Athletic footwear' },
  hoodie: { e: '🧥', h: 'Has a pocket and a hood' },
  sweatshirt: { e: '👕', h: 'Warm and comfortable' },
  overalls: { e: '👖', h: 'Denim with straps' },
  dungarees: { e: '👖', h: 'Workwear with straps' },
  raincoat: { e: '🧥', h: 'Keeps you dry' },
  windbreaker: { e: '🧥', h: 'Blocks the breeze' },

  // Nature
  thunder: { e: '🌩️', h: 'A loud boom in the sky' },
  lightning: { e: '⚡', h: 'A bright flash in the sky' },
  hill: { e: '⛰️', h: 'Walk up to the top' },
  mountain: { e: '🏔️', h: 'Very tall and rocky' },
  river: { e: '🏞️', h: 'Flowing water' },
  stream: { e: '🏞️', h: 'A small flow of water' },
  fog: { e: '🌫️', h: 'A thick cloud on the ground' },
  mist: { e: '🌫️', h: 'Light drops in the air' },
  sunset: { e: '🌇', h: 'When the day ends' },
  sunrise: { e: '🌅', h: 'When the day begins' },
  tornado: { e: '🌪️', h: 'A spinning funnel of wind' },
  cyclone: { e: '🌀', h: 'A massive storm' },
  glacier: { e: '🧊', h: 'A giant block of ice' },
  iceberg: { e: '🧊', h: 'Floating in the freezing ocean' },
  coral: { e: '🪸', h: 'Colorful underwater life' },
  reef: { e: '🪸', h: 'A rocky underwater ridge' },
  dune: { e: '🏜️', h: 'A hill of sand' },
  sandbar: { e: '🏝️', h: 'A ridge of sand in the water' },
  avalanche: { e: '🏔️', h: 'Snow falling down fast' },
  landslide: { e: '⛰️', h: 'Rocks falling down fast' },

  // Jobs
  doctor: { e: '🩺', h: 'Treats sick people' },
  nurse: { e: '💉', h: 'Helps the patients' },
  teacher: { e: '👩‍🏫', h: 'Educates the students' },
  tutor: { e: '👨‍🏫', h: 'Helps you study' },
  pilot: { e: '✈️', h: 'Flies the plane' },
  astronaut: { e: '🚀', h: 'Travels to space' },
  chef: { e: '👨‍🍳', h: 'Cooks the meals' },
  baker: { e: '🥖', h: 'Makes the bread' },
  lawyer: { e: '⚖️', h: 'Argues in court' },
  judge: { e: '⚖️', h: 'Makes the final decision' },
  architect: { e: '📐', h: 'Designs the buildings' },
  engineer: { e: '⚙️', h: 'Builds and designs' },
  journalist: { e: '📰', h: 'Writes the news' },
  reporter: { e: '🎤', h: 'Tells you the news' },
  sailor: { e: '⚓', h: 'Works on a ship' },
  soldier: { e: '🪖', h: 'Fights for the country' },
  barber: { e: '💈', h: 'Cuts your hair' },
  hairdresser: { e: '✂️', h: 'Styles your hair' },
  plumber: { e: '🔧', h: 'Fixes the pipes' },
  electrician: { e: '⚡', h: 'Fixes the wiring' },

  // Transport
  helicopter: { e: '🚁', h: 'Has spinning blades on top' },
  aeroplane: { e: '✈️', h: 'Flies high with wings' },
  submarine: { e: '🚢', h: 'Travels underwater' },
  yacht: { e: '🛥️', h: 'A fancy boat' },
  tram: { e: '🚋', h: 'Rides on rails in the city' },
  subway: { e: '🚇', h: 'Rides on rails underground' },
  scooter: { e: '🛵', h: 'A small motor on two wheels' },
  moped: { e: '🏍️', h: 'A motorized bike' },
  canoe: { e: '🛶', h: 'Row it with a paddle' },
  kayak: { e: '🛶', h: 'Row it with a double paddle' },
  bulldozer: { e: '🚜', h: 'Pushes heavy dirt' },
  excavator: { e: '🏗️', h: 'Digs deep holes' },
  carriage: { e: '🎠', h: 'Pulled by a horse' },
  chariot: { e: '🏎️', h: 'Raced in ancient times' },
  ferry: { e: '⛴️', h: 'Carries cars across the water' },
  "cruise ship": { e: '🛳️', h: 'A floating hotel' },

  // Tech
  laptop: { e: '💻', h: 'Folds closed to carry' },
  tablet: { e: '📱', h: 'A large touchscreen' },
  keyboard: { e: '⌨️', h: 'Type on the keys' },
  keypad: { e: '🔢', h: 'Punch in the numbers' },
  router: { e: '📶', h: 'Gives you WiFi' },
  modem: { e: '🔌', h: 'Connects you to the internet' },
  printer: { e: '🖨️', h: 'Puts ink on paper' },
  scanner: { e: '📠', h: 'Turns paper into a file' },
  headphones: { e: '🎧', h: 'Wear them over your ears' },
  earbuds: { e: '🔈', h: 'Put them in your ears' },
  drone: { e: '🛸', h: 'Flies by remote control' },
  "remote car": { e: '🏎️', h: 'Drive it with a controller' },
  smartwatch: { e: '⌚', h: 'Tells time and reads texts' },
  "fitness band": { e: '📟', h: 'Tracks your steps' }
};

const catEmojis = { Animals: '🐾', Food: '🍽️', Places: '📍', Objects: '📦', Activities: '🏃', Clothing: '👕', Nature: '🌿', Jobs: '💼', Transport: '🚀', Tech: '🔌' };

const dict = {};

WORD_PAIRS.forEach(p => {
  const mw = p.mainWord.toLowerCase();
  const iw = p.imposterWord.toLowerCase();

  dict[mw] = { 
    emoji: customMapping[mw]?.e || catEmojis[p.category] || '✨', 
    meaning: customMapping[mw]?.h || ('A ' + p.category.toLowerCase() + ' term'),
    isImposter: false
  };

  dict[iw] = { 
    emoji: customMapping[iw]?.e || catEmojis[p.category] || '✨', 
    meaning: customMapping[iw]?.h || ('A ' + p.category.toLowerCase() + ' term'),
    isImposter: true
  };
});

fs.writeFileSync('./client/src/wordDictionary.js', 'export const WORD_DICTIONARY = ' + JSON.stringify(dict, null, 2) + ';');
console.log('Dictionary generated successfully.');
